In [1]:
import pandas as pd
df = pd.read_csv(r'C:\Users\nima rayaneh novin\Desktop\python_work\House_price_prediction_system\data\ads.csv', encoding='utf-8-sig')

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   token             100 non-null    object
 1   category          100 non-null    object
 2   last_modified_at  100 non-null    object
 3   city              100 non-null    object
 4   title             100 non-null    object
 5   price             100 non-null    int64
 6   size              100 non-null    int64
 7   year              100 non-null    int64
 8   has_parking       100 non-null    int64
 9   has_elevator      100 non-null    int64
 10  rooms             100 non-null    object
 11  floor             100 non-null    int64
dtypes: int64(6), object(6)
memory usage: 9.5+ KB

In [3]:
df.describe()

,price,size,year,has_parking,has_elevator,floor
count,1.000000e+02,100.000000,100.000000,100.000000,100.000000,100.000000
mean,9.440700e+09,61.140000,1393.080000,0.650000,0.620000,2.220000
std,5.378781e+09,21.145012,8.437147,0.479372,0.487832,1.425454
min,4.100000e+09,30.000000,1370.000000,0.000000,0.000000,-1.000000
25%,5.962500e+09,47.000000,1386.000000,0.000000,0.000000,1.000000
50%,8.550000e+09,55.000000,1395.000000,1.000000,1.000000,2.000000
75%,1.103750e+10,70.000000,1400.000000,1.000000,1.000000,3.000000
max,4.480000e+10,147.000000,1405.000000,1.000000,1.000000,5.000000

In [4]:
df.head()

,token,category,last_modified_at,city,title,price,size,year,has_parking,has_elevator,rooms,floor
0,ga_AsEaz,apartment-sell,2026-07-20 18:59:36,tehran,سرمایه گذاری در ملک باسودتضمینی ۶۰۰ میلیون درماه,5100000000,53,1398,1,1,یک,1
1,ga2MUUg7,apartment-sell,2026-07-20 15:34:02,tehran,70متر/تکواحدی/فول/2 پارکینگه/کلیددراختیار,11800000000,70,1395,1,1,دو,2
2,ga4cynNZ,apartment-sell,2026-07-20 16:13:38,tehran,۶۰ متر دوخواب پارکینگ دار طبقه اول مرتضوی,9750000000,60,1384,1,0,دو,1
3,gaAd-C5L,apartment-sell,2026-07-20 15:52:27,tehran,تضمین اصل سرمایه به همراه سود چشمگیر,5150000000,43,1404,1,1,یک,2
4,gaAlODVZ,apartment-sell,2026-07-20 16:09:56,tehran,۴۴متر/سرمایه گذاری کوتاه مدت/سود۶۰۰میلیون,4580000000,44,1399,1,1,یک,3

In [5]:
df

,token,category,last_modified_at,city,title,price,size,year,has_parking,has_elevator,rooms,floor
0,ga_AsEaz,apartment-sell,2026-07-20 18:59:36,tehran,سرمایه گذاری در ملک باسودتضمینی ۶۰۰ میلیون درماه,5100000000,53,1398,1,1,یک,1
1,ga2MUUg7,apartment-sell,2026-07-20 15:34:02,tehran,70متر/تکواحدی/فول/2 پارکینگه/کلیددراختیار,11800000000,70,1395,1,1,دو,2
2,ga4cynNZ,apartment-sell,2026-07-20 16:13:38,tehran,۶۰ متر دوخواب پارکینگ دار طبقه اول مرتضوی,9750000000,60,1384,1,0,دو,1
3,gaAd-C5L,apartment-sell,2026-07-20 15:52:27,tehran,تضمین اصل سرمایه به همراه سود چشمگیر,5150000000,43,1404,1,1,یک,2
4,gaAlODVZ,apartment-sell,2026-07-20 16:09:56,tehran,۴۴متر/سرمایه گذاری کوتاه مدت/سود۶۰۰میلیون,4580000000,44,1399,1,1,یک,3
...,...,...,...,...,...,...,...,...,...,...,...,...
95,gaY5JGxx,apartment-sell,2026-07-20 17:21:32,tehran,۹۵ متر * تکواحدی * غرق نور * فول امکانات,16500000000,95,1405,1,1,دو,2
96,gaYp6vXc,apartment-sell,2026-07-20 16:46:26,tehran,۵۶متر یک خواب با اسانسور تک واحدی,9200000000,56,1394,0,1,یک,3
97,gaYRozM5,apartment-sell,2026-07-20 15:52:55,tehran,بوستان سعدی بین کارون و قصرالدشت42متر کلید نخورده,10900000000,42,1405,0,1,یک,2
98,gaZpb_NQ,apartment-sell,2026-07-20 15:52:06,tehran,تک واحدی بوستان سعدی,6900000000,62,1387,0,0,دو,-1
99,QanLbnZd,apartment-sell,2026-07-20 15:06:35,tehran,56متراستادمعین/فرصت ویژه سرمایه گذاری,4550000000,56,1402,1,1,یک,3

In [6]:
df.isnull().sum()

token               0
category            0
last_modified_at    0
city                0
title               0
price               0
size                0
year                0
has_parking         0
has_elevator        0
rooms               0
floor               0
dtype: int64

In [17]:
df["rooms"] = df["rooms"].map({"یک": 1, "دو": 2,"سه": 3})

In [21]:
df.head()

,token,category,last_modified_at,city,title,price,size,year,has_parking,has_elevator,rooms,floor
0,ga_AsEaz,apartment-sell,2026-07-20 18:59:36,tehran,سرمایه گذاری در ملک باسودتضمینی ۶۰۰ میلیون درماه,5100000000,53,1398,1,1,1,1
1,ga2MUUg7,apartment-sell,2026-07-20 15:34:02,tehran,70متر/تکواحدی/فول/2 پارکینگه/کلیددراختیار,11800000000,70,1395,1,1,2,2
2,ga4cynNZ,apartment-sell,2026-07-20 16:13:38,tehran,۶۰ متر دوخواب پارکینگ دار طبقه اول مرتضوی,9750000000,60,1384,1,0,2,1
3,gaAd-C5L,apartment-sell,2026-07-20 15:52:27,tehran,تضمین اصل سرمایه به همراه سود چشمگیر,5150000000,43,1404,1,1,1,2
4,gaAlODVZ,apartment-sell,2026-07-20 16:09:56,tehran,۴۴متر/سرمایه گذاری کوتاه مدت/سود۶۰۰میلیون,4580000000,44,1399,1,1,1,3

In [22]:
X = df[["size", "rooms", "year", "floor", "has_parking", "has_elevator"]]
Y = df["price"]

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [38]:
from sklearn.ensemble import RandomForestRegressor
import joblib

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, Y_train)
joblib.dump(model, "predicting_price.pkl")

['predicting_price.pkl']

In [33]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest": RandomForestRegressor(),
}

for name, model in models.items():
    model.fit(X_train, Y_train)
    y_pred = model.predict(X_test)

    print(name)
    print("MAE:", mean_absolute_error(Y_test, y_pred))
    print("RMSE:", np.sqrt(mean_squared_error(Y_test, y_pred)))
    print("R2:", r2_score(Y_test, y_pred))
    print("----------------")

Linear Regression
MAE: 1889173408.224308
RMSE: 2099448197.6972263
R2: 0.793920751270245
----------------
Decision Tree
MAE: 1635000000.0
RMSE: 2565256322.4753976
R2: 0.6923297748440852
----------------
Random Forest
MAE: 1632940000.0
RMSE: 2156311520.397737
R2: 0.7826063059272153
----------------